# Generated by Django 5.2 on 2025-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
