# Generated by Django 5.2 on 2025-04-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_initials'),
    ]

    operations = [
    ]
