# Generated by Django 5.2 on 2025-04-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_user'),
    ]

    operations = [
    ]
