# Generated by Django 5.2 on 2025-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='kanban_category',
            field=models.CharField(choices=[('Todo', 'To Do'), ('InProgress', 'In Progress'), ('AwaitFeedback', 'Await Feedback'), ('Done', 'Done')], default='Todo', max_length=50),
        ),
    ]
